services:
  postgres:
    image: postgres:17
    container_name: career-hub-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: career_hub
      POSTGRES_USER: careerhub
      POSTGRES_PASSWORD: careerhub

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
